<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-9VL2DDV" failures="1" tests="5" name="Test-Runner-Edge" time="0.387" errors="0" timestamp="2024-03-13T11:51:02 IST">
  <testcase classname="practice.TestNGPratice3" name="UpdateContact" time="0.036"/>
  <testcase classname="practice.TestNGPratice3" name="createContact" time="0.003"/>
  <testcase classname="practice.TestNGPratice4" name="createContact" time="0.054">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at practice.TestNGPratice4.createContact(TestNGPratice4.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- createContact -->
  <testcase classname="practice.TestNGPratice4" name="deleteContact" time="0.0">
    <skipped/>
  </testcase> <!-- deleteContact -->
  <testcase classname="practice.TestNGPratice4" name="UpdateContact" time="0.0">
    <skipped/>
  </testcase> <!-- UpdateContact -->
  <testcase classname="practice.TestNGPratice3" name="deleteContact" time="0.0">
    <ignored/>
  </testcase> <!-- deleteContact -->
</testsuite> <!-- Test-Runner-Edge -->
